development:
  adapter: mysql
  database: sports_development
  username: root
  password:
  host: localhost
  socket: /tmp/mysql.sock

test:
  adapter: mysql
  database: sports_test
  username: root
  password:
  host: localhost
  socket: /tmp/mysql.sock

production:
  adapter: mysql
  database: sports_production
  username: root
  password: 
  host: localhost
  socket: /tmp/mysql.sock
