development:
  adapter: mysql
  database: sports_development
  username: root
  password:
  host: localhost

test:
  adapter: mysql
  database: sports_test
  username: root
  password:
  host: localhost

production:
  adapter: mysql
  database: sports_production
  username: root
  password: 
  host: localhost
